version: '3.3'
services:
  nginx:
    environment:
      TZ: Asia/Tokyo
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/files/public:/usr/share/nginx/html
      - ./nginx/files/config/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/docker/nginx/:/var/log/nginx/
    networks:
      - web-nw

  jenkins-master:
    environment:
      TZ: Asia/Tokyo
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - '9080:8080'
      - '5000:5000'
    volumes:
      - /var/log/docker/jenkins/:/var/jenkins_home
    networks:
      - jenkins-nw

  jenkins-slave001:
    environment:
      TZ: Asia/Tokyo
      #- JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAxxxxxxxxxxxxxxxx
    image: jenkins/jenkins:lts
    container_name: jenkins-slave001
    networks:
      - jenkins-nw
      - web-nw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web-nw:
    external: true
  jenkins-nw:
    external: true
