version: '3.3'
services:
  nginx:
    #build: ./nginx/files
    environment:
      TZ: Asia/Tokyo
    image: nginx
    container_name: nginx
    ports:
        - "8080:80"
    volumes:
        - ./nginx/files/public:/usr/share/nginx/html
        - ./nginx/files/config/default.conf:/etc/nginx/conf.d/default.conf
        - /var/log/docker/nginx/:/var/log/nginx/

  jenkins:
    image: jenkins
    container_name: jenkins
    ports:
      - '9080:8080'
      - '5000:5000'
    volumes:
      - /var/log/docker/jenkins/:/var/jenkins_home
