version: '3'
services:
  jmeter-node01:
    image: vinsdocker/jmmaster
    container_name: jmeter-node01
    tty: true
    networks:
        - automation
    ports:
        - "18080:80"
    volumes:
        - ./jmeter_scenario/50Thread-10access.jmx:/jmeter/apache-jmeter-3.3/bin/50Thread-10access.jmx
    command: bash -c "jmeter -n -t /jmeter/apache-jmeter-3.3/bin/50Thread-10access.jmx"
#  jmeter-node02:
#    image: vinsdocker/jmserver
#    container_name: jmeter-node02
#    tty: true
#    networks:
#      - automation
#    ports:
#        - "28080:80"
#    volumes:
#         - ./jmeter_scenario/50Thread-10access.jmx:/jmeter/apache-jmeter-3.3/bin/50Thread-10access.jmx
#    command: bash -c "jmeter -n -t /jmeter/apache-jmeter-3.3/bin/50Thread-10access.jmx"

networks:
  automation:
    external: "true"
